username=company.admin
url=https://iqxoratest4.iqxora.com/#login
browser=chrome
driverlocation=/home/gautham/Documents/latestchrome120/chrome-linux64
password=123456
projectname=Testing00334
projectname1=folderspace12
foldername=testapp1
searchname=folder222
foldername1=testapp2
foldername2=testapp3
foldername3=testapp4
foldername4=testapp5
foldername5=testapp6
foldername6=testapp7
foldername7=testapp8
renamefolder=testapp9
renamefile=testapp10
deletename=testapp11
deletenamefile=testapp12
remaindername=testapp13
remaimdername1=testapp14
bookmarkfoldercreate=testapp15
searchfoldersharebyme=folder16
searchfoldersharewithme=folder23
bookmarkrename=testapp16
bookmarksearchmove=folder115
advancesearch=11-801-24-06007.pdf
advancesearchcontent=Demonstration of DOCX support in calibre
quicksearch=11-801-24-06007.pdf
sdnote=testapp17
projectfoldername=testapp18
user=gow
user1=albert
user2=babu
group=TechSupport
group1=TEK
partner=Abnormal Partner Test 3
filename=/home/gautham/Documents/11-801-24-06007.pdf







