username=company.admin
url=https://iqxoratest4.iqxora.com/#login
browser=chrome
driverlocation=/home/gautham/Documents/latestchrome120/chrome-linux64
password=123456
projectname=Testing0033424
projectname1=folderspace
foldername=testapp157
searchname=folder222
foldername1=testapp2157
foldername2=testapp3157
foldername3=testapp457
foldername4=testapp5357w1
foldername5=testapp65457
foldername6=testapp757
foldername7=testapp857
renamefolder=testapp9157
renamefile=testapp1057
deletename=testapp1157
deletenamefile=testapp1257
remaindername=testapp1357
remaimdername1=testapp1457
bookmarkfoldercreate=testapp1557
searchfoldersharebyme=folder16
searchfoldersharewithme=folder23
bookmarkrename=testapp1657
bookmarksearchmove=folder115
advancesearch=11-801-24-06007.pdf
advancesearchcontent=Demonstration of DOCX support in calibre
quicksearch=11-801-24-06007.pdf
sdnote=testapp1757
projectfoldername=testapp1897
user=gow
user1=albert
user2=babu
group=TechSupport
group1=TEK
partner=Abnormal Partner Test 3
filename=/home/gautham/Documents/11-801-24-06007.pdf







