username=company.admin
url=https://iqxoratest4.iqxora.com/#login
browser=chrome
driverlocation=/home/gautham/Documents/latestchrome120/chrome-linux64
password=123456
projectname=Testing003
projectname1=folder2
foldername=latestfolder1
searchname=folder222
foldername1=latestfolder2
foldername2=latestfolder3
foldername3=latestfolder4
foldername4=latestfolder44
foldername5=latestfolder33
foldername6=latestfolder7
foldername7=latestfolder8
renamefolder=latestfolder9
renamefile=latestfolder10
deletename=latestfolder11
deletenamefile=latestfolder12
remaindername=latestfolder13
remaimdername1=latestfolder14
bookmarkfoldercreate=latestfolder15
searchfoldersharebyme=folder16
searchfoldersharewithme=folder23
bookmarkrename=latestfolder16
bookmarksearchmove=folder115
advancesearch=gowtham2.pdf
advancesearchcontent=Low Code Development
quicksearch=gowtham2.pdf
sdnote=latestfolder17
projectfoldername=latestfolder18
user=gow
user1=albert
user2=babu
group=TechSupport
group1=TEK
partner=Abnormal Partner Test 3







